#!/usr/bin/env bash

location="-37.8139,144.9630"
units=ca
url="https://api.darksky.net/forecast/${WEATHER_API_KEY}/${location}?units=${units}&exclude=minutely,hourly,daily,alerts,flags"

api_response=$(curl -s "${url}")

temperature=$(echo "${api_response}" | jq '.currently.temperature' | xargs printf '%.*f\n' 0)
weather_icon=$(echo "${api_response}" | jq '.currently.icon')
summary=$(echo "${api_response}" | jq '.currently.summary' | tr -d '"')

case "${weather_icon}" in
  '"clear-day"')
    icon=""
    ;;
  '"clear-night"')
    icon=""
    ;;
  '"rain"')
    icon=""
    ;;
  '"snow"')
    icon=""
    ;;
  '"sleet"')
    icon=""
    ;;
  '"wind"')
    icon=""
    ;;
  '"fog"')
    icon=""
    ;;
  '"cloudy"')
    icon=""
    ;;
  '"partly-cloudy-day"')
    icon=""
    ;;
  '"partly-cloudy-night"')
    icon=""
    ;;
esac

echo -n "%{F#01AB84}${icon}%{F-} ${summary}  %{F#01AB84}%{F-} ${temperature} °C"
